### ISSUE TITLE
Not working for certain icons

### ISSUE THREAD

**Issue by Aariq** [jmgirard/lordicon#3]
The examples on the README work for me, but I'm having trouble getting this to work with certain icons.  For example, the REST API icon doesn't show up with `{{< li dmgxtuzn >}}`.  It shows up if I download the .json file and use `{{< lif api.json >}}`, but it isn't animated even if I add `trigger=loop`.  I don't have any issues getting it to work by just copying in the HTML:

```html
<script src="https://cdn.lordicon.com/lordicon.js"></script>
<lord-icon
    src="https://cdn.lordicon.com/dmgxtuzn.json"
    trigger="hover"
    style="width:250px;height:250px">
</lord-icon>
```

**Comment by jmgirard** [comment]
I made a new release with updated dependencies. The following now works for me:
`{{< li dmgxtuzn trigger=loop >}}`

However, note that `{{< li dmgxtuzn >}}` will appear blank because the first frame of the animation is just white.

**Comment by jmgirard** [comment]
This is now fixed in https://github.com/jmgirard/lordicon/releases/tag/v0.4.0
